export const PRODUCTS = [
  {
    name: 'Taza HP - Reliquias de la Muerte',
    price: 10,
    category: 'Harry Potter',
    image: '/taza1.png',
    type: 'comun-cup',
  },
  {
    name: 'Taza Mágica Sherlock Holmes',
    price: 15,
    category: 'Series',
    image: '/sherlockMug.png',
    type: 'magic-cup',
  },
  {
    name: 'Taza Pokemon - Mewtwoo',
    price: 10,
    category: 'Anime',
    image: '/taza2.png',
    type: 'comun-cup',
  },
  {
    name: 'Vaso Térmico HP - Expresso Patronum',
    price: 12,
    category: 'Harry Potter',
    image: '/potterMug.png',
    type: 'termic-mug',
  },
  {
    name: 'Taza Sailor Moon',
    price: 10,
    category: 'Anime',
    image: '/taza4.png',
    type: 'comun-cup',
  },
  {
    name: 'Taza Mágica Alicia en el País de las Maravillas',
    price: 15,
    category: 'Disney',
    image: '/aliciaMagic.png',
    type: 'magic-cup',
  },
  {
    name: 'Vaso Térmico Friends',
    price: 12,
    category: 'Series',
    image: '/friendsMug.png',
    type: 'termic-mug',
  },
  {
    name: 'Taza Breaking Bad - Coffee Break',
    price: 10,
    category: 'Series',
    image: '/taza8.png',
    type: 'comun-cup',
  },
  {
    name: 'Taza Los Simpsons - Marge',
    price: 10,
    category: 'Series',
    image: '/taza10.png',
    type: 'comun-cup',
  },
  {
    name: 'Taza Mágica HP- Casa de Hogwarts',
    price: 15,
    category: 'Harry Potter',
    image: '/potterMagic.png',
    type: 'magic-cup',
  },
  {
    name: 'Taza Deadpool',
    price: 10,
    category: 'Superheroes',
    image: '/taza6.png',
    type: 'comun-mug',
  },
  {
    name: 'Vaso Térmico Totoro',
    price: 12,
    category: 'Anime',
    image: '/totoroMug.png',
    type: 'comun-mug',
  },
];
